name: Cypress Tests CI/CD

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      suite:
        description: "¿Qué suite ejecutar?"
        required: true
        default: "all"
        type: choice
        options:
          - login
          - objetivos
          - all
      branch:
        description: "¿En qué rama correr?"
        required: false
        default: "main"

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🔑 Configurar variables de entorno
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV
          echo "NORMAL_USER=${{ secrets.NORMAL_USER }}" >> $GITHUB_ENV
          echo "NORMAL_PASS=${{ secrets.NORMAL_PASS }}" >> $GITHUB_ENV
          echo "SPECIAL_USER=${{ secrets.SPECIAL_USER }}" >> $GITHUB_ENV
          echo "SPECIALUSER_PASS=${{ secrets.SPECIALUSER_PASS }}" >> $GITHUB_ENV

      - name: 🚀 Ejecutar pruebas seleccionadas
        run: |
          if [ "${{ github.event.inputs.suite }}" == "login" ]; then
            npx cypress run --spec "cypress/e2e/Login/**/*"
          elif [ "${{ github.event.inputs.suite }}" == "objetivos" ]; then
            npx cypress run --spec "cypress/e2e/Cards/**/*"
          else
            npx cypress run
          fi

      - name: 📊 Guardar reportes de pruebas
        uses: actions/upload-artifact@v4
        with:
          name: Cypress Reports
          path: cypress/reports
