name: Cypress Tests CI/CD

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # También permite ejecutarlo manualmente

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v3

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🔑 Configurar variables de entorno
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV
          echo "ADMIN_USER=${{ secrets.ADMIN_USER }}" >> $GITHUB_ENV
          echo "ADMIN_USER_TWO=${{ secrets.ADMIN_USER_TWO }}" >> $GITHUB_ENV
          echo "ADMIN_PASS=${{ secrets.ADMIN_PASS }}" >> $GITHUB_ENV
          echo "NOTEXIST_USER=${{ secrets.NOTEXIST_USER }}" >> $GITHUB_ENV
          echo "BROKE_USER_ONE=${{ secrets.BROKE_USER_ONE }}" >> $GITHUB_ENV
          echo "BROKE_USER_TWO=${{ secrets.BROKE_USER_TWO }}" >> $GITHUB_ENV
          echo "BROKE_USER_THREE=${{ secrets.BROKE_USER_THREE }}" >> $GITHUB_ENV
          echo "BROKE_USER_FOUR=${{ secrets.BROKE_USER_FOUR }}" >> $GITHUB_ENV
          echo "BROKE_USER_SIX=${{ secrets.BROKE_USER_SIX }}" >> $GITHUB_ENV
          echo "BROKE_PASSWORD_ONE=${{ secrets.BROKE_PASSWORD_ONE }}" >> $GITHUB_ENV
          echo "BROKE_PASSWORD_TWO=${{ secrets.BROKE_PASSWORD_TWO }}" >> $GITHUB_ENV
          echo "BROKE_PASSWORD_THREE=${{ secrets.BROKE_PASSWORD_THREE }}" >> $GITHUB_ENV


      - name: 🚀 Ejecutar pruebas en Cypress
        run: npx cypress run

      - name: 📊 Guardar reportes de pruebas
        uses: actions/upload-artifact@v3
        with:
          name: Cypress Reports
          path: cypress/reports
