name: Cypress Tests CI/CD

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # También permite ejecutarlo manualmente

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v3

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🔑 Configurar variables de entorno
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV
          echo "NORMAL_USER=${{ secrets.NORMAL_USER }}" >> $GITHUB_ENV
          echo "NORMAL_PASS=${{ secrets.NORMAL_PASS }}" >> $GITHUB_ENV
          echo "SPECIAL_USER=${{ secrets.SPECIAL_USER }}" >> $GITHUB_ENV
          echo "SPECIALUSER_PASS=${{ secrets.SPECIALUSER_PASS }}" >> $GITHUB_ENV

      - name: 🚀 Ejecutar solo pruebas de login en Cypress
        if: github.ref == 'refs/heads/test/001/login'
        run: npx cypress run --spec "cypress/e2e/Login/**/*"

      - name: 🚀 Ejecutar todas las pruebas (otras ramas)
        if: github.ref != 'refs/heads/test/001/login'
        run: npx cypress run

      - name: 📊 Guardar reportes de pruebas
        uses: actions/upload-artifact@v4
        with:
          name: Cypress Reports
          path: cypress/reports
